id: b85cad527a8448c0b9b273f8a94be0aa
initial_creation_type: ocr
source_metadata:
  volumes:
    0cdbfdf935234644af46558bc642c799:
      base_file: v092.txt
      image_group_id: I1PD95938
      title: ''
      total_pages: 1484
      volume_number: 93
